site_name: World's Innovation
site_description: Startup céer à l'inphb pour la réalisation de projets innovants
site_author: Tenemahan Coulibaly
copyright : Copyright 2025 Tenemahan Coulibaly - Creative Commons Attribution Non Commercial

site_url: https://mydomain.org/mysite
theme:
  name: material
  favicon: images/favicon.png
  language: en
  icon:
    logo: fontawesome/solid/hat-cowboy
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - search.share
    
   
     
  palette:
    - scheme: default
      toggle: default
      primary: indigo
      accent: blue
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - scheme: default
      primary: blue
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  font:
    text: Roboto
    code: Fira Code
plugins:
    - offline
    - tags
    - search
    - git-revision-date-localized
    - privacy:
      concurrency: 1
    - social:
      github: https://github.com/Coul-Tene/WLInnova 


nav:
  - Accueil: index.md
  - Téléchargement: telechargement.md
markdown_extensions:
  - footnotes  
  - attr_list
  