site_name: World's Innovation
site_description: Startup céer à l'inphb pour la réalisation de projets innovants
site_author: Tenemahan Coulibaly
site_url: https://mydomain.org/mysite
theme:
  name: material
  favicon: images/favicon.png
  language: en
  icon:
    logo: fontawesome/solid/hat-cowboy
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - announce.dismiss
    - navigation.footer
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - search.share
   
     
  palette:
   # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode

    # Palette toggle for light mode
    - scheme: default
      primary: blue
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode  
plugins:
    - offline
    - search
